#!/bin/bash
function ConnectToServer()
{
	read -p "Which server would you like to connect?
	server1
	server2[username password hostname]" answer answer1 answer2 answer3
	case $answer in
	server1) sshpass -p yourPassword ssh yourUsername@yourHostname
	;;
	server2) sshpass -p $answer2 ssh $answer1@$answer3
	;;
	esac
}

SERVICE='tor'
if ps ax|tr -s " "| cut -d " " -f6 | grep -w $SERVICE > /dev/null
then
    echo "$SERVICE service is running."
	ConnectToServer
else
    echo "$SERVICE is not running. Starting..."
    networksetup -setsocksfirewallproxystate Wi-Fi on
    echo "SOCKS proxy on."
    tor&
    sleep 10
    ConnectToServer
fi
